courses/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    # name index is taken from {% url 'courses:index' %}
    # path('', views.index, name='index'),
    path(route='', view=views.CourseListView.as_view(), name='index'),
    path('logout/', views.logout_request, name='logout'),
    path('registration/', views.registration_request, name='registration'),
    path('login/', views.login_request, name='login'),
    # path('<int:pk>/', views.CourseDetailView.as_view(), name='course_details'),
    # ex: course/5/
    path('grade/<int:course_id>/', views.course_details, name='course_details'),
    # route to start the test view
    path('grade/<int:course_id>/test/<int:lesson_id>/', views.start_test, name='start_test'),
    path('grade/<int:course_id>/submit_test/<int:lesson_id>/', views.submit_test, name='submit_course_test'),
    # route for show_exam_result view
    path('result/<int:course_id>/<int:lesson_id>/<int:submission_id>/', views.show_exam_result, name='show_exam_result'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

filicourses/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('courses/', include('courses.urls')),
    # above means: any urls that start with courses/ → send them to the urls module in the courses app
    # we write this line of code only once
    # below works well for index.html for the {% url 'courses:logout' %} for example
    # https://stackoverflow.com/questions/41883254/django-is-not-a-registered-namespace
    path('', include(('courses.urls', 'courses'), namespace='courses')),
]

courses/models.py
import sys
from django.utils.timezone import now
try:
    from django.db import models
except Exception:
    print("There was an error loading Django modules. Do you have Django installed?")
    sys.exit()

from django.conf import settings
import uuid


# Instructor model
class Instructor(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    full_time = models.BooleanField(default=True)
    total_learners = models.IntegerField(default=1)

    def __str__(self):
        return self.user.username


# grade / courses
class Course(models.Model):
    name = models.CharField(max_length=30, default='Course/Grade')
    description = models.CharField(max_length=1000)
    image = models.CharField(max_length=2083)
    pub_date = models.DateField(null=True)

    def __str__(self):
        return "Name: " + self.name + "," + \
               "Description: " + self.description


# lesson / list of test options
class Lesson(models.Model):
    title = models.CharField(max_length=200, default="Lesson title")
    order = models.IntegerField(default=0)
    image = models.CharField(max_length=2083, default="none")
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    content = models.TextField()

    # for the admin. Returns the title lesson
    def __str__(self):
        return self.title + " - " + self.course.name


# Create a Question Model
class Question(models.Model):
    question_text = models.CharField(max_length=200, default="Question")
    grade = models.IntegerField(default=1)
    image = models.CharField(max_length=2083, default="none")
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)

    # for the admin. Return the question
    def __str__(self):
        return self.question_text

    def is_get_score(self, selected_ids):
        all_answers = self.choice_set.filter(is_correct=True).count()
        selected_correct = self.choice_set.filter(is_correct=True, id__in=selected_ids).count()
        selected_wrong = self.choice_set.filter(is_correct=False, id__in=selected_ids).count()

        if all_answers == selected_correct and selected_wrong == 0:
            return True
        else:
            return False

    def not_selected(self, selected_ids, not_selected):
        missing = self.choice_set.filter(is_correct=True).exclude(id__in=selected_ids)
        for el in missing:
            not_selected.append(el)


#  Create a Choice Model
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    is_correct = models.BooleanField(default=True)

    def __str__(self):
        return self.choice_text


class Submission(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choices = models.ManyToManyField(Choice)

    def __str__(self):
        return f'{self.question} {self.choices}'

courses/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect
from .models import Course, Lesson, Choice, Question, Submission
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
import logging
from django.urls import reverse
from django.views import generic
# Get an instance of a logger
logger = logging.getLogger(__name__)


def registration_request(request):
    context = {}
    if request.method == 'GET':
        # remove courses/ and works
        # link displays registration only. Not user_registration_bootstrap.html
        return render(request, 'user_registration_bootstrap.html', context)
    elif request.method == 'POST':
        # Check if user exists
        username = request.POST['username']
        password = request.POST['psw']
        first_name = request.POST['firstname']
        last_name = request.POST['lastname']
        user_exist = False
        try:
            User.objects.get(username=username)
            user_exist = True
        except:
            logger.error("New user")
        if not user_exist:
            user = User.objects.create_user(username=username, first_name=first_name, last_name=last_name,
                                            password=password)
            login(request, user)
            return redirect("courses:index")
        else:
            context['message'] = "User already exists."
            return render(request, 'user_registration_bootstrap.html', context)


def login_request(request):
    context = {}
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['psw']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('courses:index')
        else:
            context['message'] = "Invalid username or password."
            return render(request, 'user_login_bootstrap.html', context)
    else:
        return render(request, 'user_login_bootstrap.html', context)


def logout_request(request):
    logout(request)
    return redirect('courses:index')


'''
def index(request):
    # Before was return HttpResponse('Hello FiliCourses')
    # return all the courses from Model Course in the database
    courses = Course.objects.all()
    # the third argument is a dictionary. This dictionary is called the context.
    # It provides data to use in a template.
    # The property called 'courses' can be accessed in the template by looping with courses
    return render(request, 'index.html', {'courses': courses})
'''


# CourseListView
class CourseListView(generic.ListView):
    template_name = 'index.html'
    context_object_name = 'courses'

    def get_queryset(self):
        # return all the courses from Model Course in the database
        courses = Course.objects.all()
        return courses


'''
class CourseDetailView(generic.DetailView):
    model = Course
    template_name = 'course_details.html'

'''


def course_details(request, course_id):
    '''
    https://stackoverflow.com/questions/19336076/django-reverse-for-detail-with-arguments-and-keyword-arguments-n
    '''
    course = get_object_or_404(Course, pk=course_id)
    return render(request, 'course_details.html', {'course': course})


def start_test(request, course_id, lesson_id):
    lesson = get_object_or_404(Lesson, pk=lesson_id)
    course = get_object_or_404(Course, pk=course_id)
    # pass course_id
    context = {'lesson': lesson, 'course': course, 'course_id': course_id}
    return render(request, 'course_test.html', context)


# Create a submit view to create an exam submission record
def submit_test(request, course_id, lesson_id):
    course = get_object_or_404(Course, pk=course_id)
    lesson = get_object_or_404(Lesson, pk=lesson_id)
    question = get_object_or_404(Question, pk=lesson_id)
    # user = request.user
    # enrollment = Enrollment.objects.get( course=course)
    # question=question is in the Submission model
    submission = Submission.objects.create(question=question)

    answers = extract_answers(request)
    for answer in answers:
        each_answer = Choice.objects.filter(id=int(answer)).get()
        submission.choices.add(each_answer)
    submission.save()

    return HttpResponseRedirect(reverse(viewname='courses:show_exam_result', args=(course_id, lesson_id, submission.id,)))


# Method to collect the selected choices from the exam form from the request object
def extract_answers(request):
    submitted_answers = []
    for key in request.POST:
        # key in post
        if key.startswith('choice'):
            value = request.POST[key]
            choice_id = int(value)
            submitted_answers.append(choice_id)
    return submitted_answers


# Create an exam result view to check if learner passed exam
def show_exam_result(request, course_id, lesson_id, submission_id):
    course = Course.objects.get(pk=course_id)
    lesson = Lesson.objects.get(pk=lesson_id)
    submission = Submission.objects.get(pk=submission_id)
    selected_ids = []
    not_selected = []
    grade = 0
    submission_choices_ids = submission.choices.values_list('pk', flat=True)

    for question in lesson.question_set.all():
        total_question = lesson.question_set.all().count()
        question.not_selected(submission_choices_ids, not_selected)
        if question.is_get_score(submission_choices_ids):
            # total grade for each question
            grade += question.grade

    # choice in exam_result_bootstrap
    for choice in submission.choices.all():
        selected_ids.append(choice.id)

    context = {'course': course, 'lesson': lesson, 'selected_ids': selected_ids,
               'grade': int(100 * grade / total_question)}
    return render(request, 'exam_result.html', context)

courses/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/courses.css' %}">
    <meta charset="UTF-8">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <title>{% block title %}Online learning tests | FiliCourses{% endblock %}</title>
<style>



</style>
</head>
<body>
    <!-- Navigation bar -->
    <nav class="navbar navbar-light bg-light">
        <div class="container">
            <div class="navbar-header">
                <!-- link to url page in app courses and look for name index -->
                <a class="navbar-brand" href="{% url 'courses:index' %}">FiliCourses</a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li>
                    <a class="btn btn-link" href="#">{{ user.first_name}}({{ user.username }})</a>
                    <a class="btn btn-link" href="{% url 'courses:logout' %}">Logout</a>
                </li>
                {% else %}
                <li>
                    <form class="form-inline" action="{% url 'courses:login' %}" method="post">
                        {% csrf_token %}
                        <div class="input-group input-group-sm">
                            <input type="text" class="form-control" placeholder="Username" name="username" >
                            <input type="password" class="form-control" placeholder="Username" name="psw" >
                            <button class="btn btn-primary btn-sm" type="submit">Login</button>
                            <a class="btn btn-link btn-sm" href="{% url 'courses:registration' %}">Sign Up</a>
                        </div>
                    </form>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
{% block content %}
<h1>Basic Home-Page</h1>
{% endblock %}
{% block footer %}
<footer>
    <!-- https://mdbootstrap.com/docs/b4/jquery/navigation/footer/ -->
    <div class="container text-center text-md-left pt-3">

        <div class="row">

            <!-- Grid column -->
            <div class="col-md-5 mt-md-0 mt-3">

            <!-- Links -->
            <h5 class="fw-bold">FiliCourses</h5>
            <p class="text-justify pl-0 col-md-11 col-xs-1">FiliCourses provides free educational quizzes for kids to increase and test their knowledge in a fun way.</p>

            </div>
            <!-- Grid column -->

            <hr class="clearfix w-100 d-md-none pb-3">

            <!-- Grid column -->
            <div class="col-md-3 mb-md-0 mb-3">

            <!-- Links -->
            <h6 class="fw-bold">Connect</h6>
            <hr
                class="mb-4 mt-0 d-inline-block mx-auto"
                style="width: 60px; background-color: #7c4dff; height: 2px"
                />
              <p>
                <a class="link-unstyled" href="#!"><i class="fa fa-facebook mr-3"></i></a>
                <a class="link-unstyled" href="#!"><i class="fa fa-twitter mr-3"></i></a>
              </p>
            </div>
            <!-- Grid column -->

            <!-- Grid column -->
            <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4 pb-3">
            <!-- Links -->
            <h6 class="fw-bold">Contact</h6>
            <hr
                class="mb-4 mt-0 d-inline-block mx-auto"
                style="width: 60px; background-color: #7c4dff; height: 2px"
                />
            <p><i class="fa fa-home mr-3"></i>New Jersey, NJ, US</p>
            <p><i class="fa fa-envelope mr-3"></i>courses@filistudio.com</p>
            </div>
            <!-- Grid column -->

        </div>
        <!-- Grid row -->

    </div>
    <!-- Footer Links -->

    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© Copyright 2022 - <a class="link-unstyled" href="{% url 'courses:index' %}"> FiliCourses.com</a>. All rights reserved.
    </div>

</footer>

    {% endblock %}
</body>
</html>

courses/templates/course_details.html
{% extends "base.html" %}
{% block title %}{{ course.name }} | FiliCourses{% endblock %}
{% block content %}
<style>
h2 {
    color: purple;
}

.btn-purple {
    background-color: purple;
    color: white;
}

.btn-purple:hover {
    background-color: #660066;
    color: white;
}

.card-header-purple {
    background-color: #FBF7FB;
}

</style>
<div class="course-list">
    <div class="container w-50 mx-auto">
        <a class="link-unstyled" href="{% url 'courses:index' %}"> Courses list</a>
    </div>
</div>
<div class="container mt-5 mb-5 min-vh-100">
    <h2 class="mb-5 start-test-title">{{ course.name }}</h2>
    <div class="row">
        <div class="card-columns-vertical col-lg-8 mt-3 mx-auto">
            {% for lesson in course.lesson_set.all %}
            <div class="card mt-4">
                <div class="card-header card-header-purple">
                    <h5>{{lesson.title}}</h5>
                    {% if lesson.image != "none" %}
                    <img class="img-fluid" src="{{ lesson.image }}">
                    {% endif %}
                </div>
                <div class="card-body">{{lesson.content}}</div>
                <!-- lesson ID: {{ lesson.id }} -->
                <!-- courses is for the folder 'courses'. start_test: name in the urls folder  -->
                <a class="btn btn-purple" href="{% url 'courses:start_test' course_id=course.id lesson_id=lesson.id %}">Start test</a>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

courses/templates/course_test.html
{% extends "base.html" %}
{% block title %}{{ lesson.title }} | FiliCourses{% endblock %}
{% block content %}
<style>


</style>
<div class="course-list">
    <div class="container w-50 mx-auto">
        <a class="link-unstyled" href="{% url 'courses:index' %}"> Courses list</a>
        > <a class="link-unstyled" href="{% url 'courses:course_details' course_id %}">{{course.name}}</a>
    </div>
</div>
<div class="container mt-5 mb-5 min-vh-100">
    <!-- lesson: from context in views def start_test. lesson.title: from model -->
    <!-- course id: {{ course_id }} -->
    <h2 class="mb-5 start-test-title">{{ lesson.title }} - Start test</h2>
    <div class="row">
        <div class="card-columns-vertical col-lg-7 mt-3 mx-auto">
        <form id="questionform" action="{% url 'courses:submit_course_test' course_id=course_id lesson_id=lesson.id %}" method="post">
            {% for question in lesson.question_set.all %}
            <div class="card mt-1 mb-3 border-secondary">
                {% if question.image != "none" %}
                <div class="card-header card-header bg-white">
                    <img class="img-fluid" src="{{ question.image }}">
                {% else %}
                <div class="card-header card-header-green">
                    <h5>{{ question.question_text}}</h5>
                    {% endif %}
                </div>
                    {% csrf_token %}
                    <div class="form-group m-3">
                        {% for choice in question.choice_set.all %}
                        <div class="form-check">
                            <!-- choice_{{ question.id } to loop through input with same name -->
                            <input type="radio" id="{{choice.id}}"
                                   name="choice_{{ question.id }}" class="form-check-input"
                                   value="{{choice.id}}" required>
                            <label for="{{choice.id}}" class="form-check-label">{{ choice.choice_text }}
                            </label>
                        </div>
                        {% endfor %}
                    </div>
            </div>
            {% endfor %}
            <input class="btn btn-success btn-block mt-2" type="submit" value="Submit">
        </form>
        </div>
    </div>
</div>
{% endblock %}

courses/templates/exam_result.html
{% extends "base.html" %}
{% block content %}
<div class="container mt-5 mb-5 min-vh-100">
    <h2 class="mb-5 start-test-title">{{ course.name }}</h2>
    <div class="row">
        <div class="col-lg-8 mt-3 mx-auto">
        {% if grade > 80 %}
            <div class="alert alert-success">
            <!--HINT Display passed info -->
            <b>Congratulations, {{ user.username }}!</b> You have passed the test with score {{ grade }}/100
            </div>
        {% else %}
            <div class="alert alert-danger">
            <!--HINT Display failed info -->
                <b>Your score is {{ grade }}/100</b> Sorry, {{ user.username }}! <a class="link-unstyled font-weight-bold" href="{% url 'courses:start_test' course_id=course.id lesson_id=lesson.id %}">
                Try again</a> or <a class="link-unstyled font-weight-bold" href="{% url 'courses:course_details' course.id %}">Try another test</a>
            </div>
        {% endif %}
        <h5 class="py-2">Results</h5>
        <div class="card-columns-vertical col-lg-10 mt-3 mx-auto">
         <!--HINT Display exam results-->
        {% for question in lesson.question_set.all %}
            <div class="card mt-1 mb-3 border-secondary">
                {% if question.image != "none" %}
                <div class="card-header card-header bg-white">
                    <img class="img-fluid" src="{{ question.image }}">
                {% else %}
                <div class="card-header card-header-green">
                    <h5>{{ question.question_text}}</h5>{{ answers }}
                    {% endif %}
                </div>
                <div class="card-body">
                    {% for choice in question.choice_set.all %}
                        {% if choice.is_correct and choice.id in selected_ids %}
                    <div class="text-success"><span class="font-weight-bold">{{ choice.choice_text }}</span> Correct!</div>
                        {% else %}
                        {% if not choice.is_correct and choice.id in selected_ids %}
                    <div class="text-danger"><span class="font-weight-bold">{{ choice.choice_text }}</span> Sorry! It's not the correct answer.</div>
                        {% else %}
                        {% if choice.is_correct %}
                    <div class="text-warning"><span class="font-weight-bold">{{ choice.choice_text }}</span> This is the correct answer</div>
                        {% else %}
                            <div>{{ choice.choice_text }}</div>
                        {% endif %}
                        {% endif %}
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        {% endfor %}
        </div>
        </div>
    </div>
</div>
{% endblock %}

courses/templates/index.html
{% extends "base.html" %}
{% block title %}Online learning tests | FiliCourses{% endblock %}
{% block content %}
<style>

@media screen and (max-width: 800px) {

    .list-grade {
        grid-template-columns: 1fr;
    }
}

</style>
<!-- width 100% to center -->
<h1 class="first-title">Online learning tests</h1>
    <div class="bg-img">
        <img src="https://filistudio.com/clink/banner-filicourses.jpg">
    </div>

    <div class="container mt-5" style="min-height: 600px;">
        {% if courses %}
            <div class="list-grade mt-5 mb-5">
            <!-- {% is called template tag in Django -->
            <!-- The courses comes from the views page.
                 It is the third argument (called the context)
                 If it is not in the context, you won't be able to render content here
                 the name in course.name comes from the Models since in the view we are return all the courses from Model Course in the database -->
            {% for course in courses %}
            <! -- https://stackhowto.com/how-to-overlay-one-div-over-another-div-using-css/ -->
                <div class="parent container">
                    <a href="{% url 'courses:course_details' course.id %}" class="text-decoration-none">
                      <div class="child1"><img src="{{ course.image }}">
                      </div>
                      <div class="child1 child2">
                          {% for lesson in course.lesson_set.all %}
                          <p class="m-0">- {{ lesson.title }}</p>
                          {% endfor %}
                      </div>
                    </a>
                </div>
            {% endfor %}
            </div>
    {% else %}
    <p>No courses are available.</p>
    {% endif %}
    </div>
</div>

{% endblock %}

courses/templates/user_registration_bootstrap.html
{% extends "base.html" %}
{% block title %} Sign Up | FiliCourses{% endblock %}
{% block content %}
<div class="container min-vh-100">
    <form action="{% url 'courses:registration' %}" method="post">
        {% csrf_token %}
        <h1>Sign Up</h1>
        <hr>
        <div class="form-group"> <!--Style second div with .form-group class -->
            <label for="username"><b>User Name</b></label>
            <input type="text" class="form-control" placeholder="Enter User Name: " name="username" required> <!--Style input with .form-control class -->
            <label for="firstname"><b>First Name</b></label>
            <input type="text" class="form-control" placeholder="Enter First Name: " name="firstname" required> <!--Style input with .form-control class -->
            <label for="lastname"><b>Last Name</b></label>
            <input type="text" class="form-control" placeholder="Enter Last Name: " name="lastname" required> <!--Style input with .form-control class -->
            <label for="psw"><b>Password</b></label>
            <input type="password" class="form-control" placeholder="Enter Password: " name="psw" required> <!--Style input with .form-control class -->
            {% if message %}
            <div class="alert alert-warning"> <!--Style the message paragraph with .alert and .alert-warning class -->
                {{ message }}
            </div>
            {% endif %}
            <button class="btn btn-primary" type="submit">Sign up</button> <!--Style button with .btn and .btn-primary class -->
        </div>
    </form>
</div>
{% endblock %}